# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zxgjUqvIApHS7_dHscKfhXsY_Qj0ghK1
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

np.random.seed(1)
x=np.arange(10)
y=np.random.rand(10)

plt.plot(x, y)
plt.show()

def f(x):
  return (x-2)*x*(x+2)

print(f(1))

print(f(np.array([1, 2, 3])))

x = np.arange(-3, 3.5, 0.5)

print(x)

plt.plot(x, f(x))

plt.show()

